name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack
          ./build.sh

      - name: Test
        run: |
          cargo test
          deno test -A
          deno bench -A

      - name: Publish package
        run: deno publish
